name = "MarineShelf"
uuid = "2a44b8da-4339-49c2-aed1-6f51696bace5"
authors = ["Alexander Robinson <alexander.robinson@awi.de> and contributors"]
version = "1.0.0-DEV"

[compat]
NCDatasets = "0.14.14"
julia = "1.10.10"
[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
